// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJyOjEpwZDeGinpPSt-18QZLOf8uraNZE',
    appId: '1:170360365765:android:3428af6b68957981a1c6ac',
    messagingSenderId: '170360365765',
    projectId: 'scrubbr-portal',
    databaseURL: 'https://scrubbr-portal-default-rtdb.firebaseio.com',
    storageBucket: 'scrubbr-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmh0VC2kUOB9ml5TXeSIR22GIdP72dLkA',
    appId: '1:170360365765:ios:3938641f6437ae2aa1c6ac',
    messagingSenderId: '170360365765',
    projectId: 'scrubbr-portal',
    databaseURL: 'https://scrubbr-portal-default-rtdb.firebaseio.com',
    storageBucket: 'scrubbr-portal.firebasestorage.app',
    iosBundleId: 'com.scrubbrllc.scrubbr.scrubbrpro.scrubbrpro',
  );
}
